# Generated by Django 3.1.2 on 2020-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalEarningOfAllCase', models.CharField(max_length=1500)),
                ('TotalEarningsOfAllSportsBetsCases', models.CharField(max_length=1500)),
                ('TotalEarningsOfAllSlotMachineCases', models.CharField(max_length=1500)),
                ('TotalEarningsOfAllOnlineCasinoCases', models.CharField(max_length=1500)),
                ('TotalEarningsOfAllWonCases', models.CharField(max_length=1500)),
                ('TotalAmountWonOfAllWonCases', models.CharField(max_length=1500)),
                ('TotalEaringsOfAllLostCases', models.CharField(max_length=1500)),
                ('TotalClaimAmountOfAllFiledLawsuitsCases', models.CharField(max_length=1500)),
                ('TotalCustomerAmountLossOfAllProcessingCases', models.CharField(max_length=1500)),
                ('TotalClaimAmountOfAllProcessingCases', models.CharField(max_length=1500)),
            ],
        ),
    ]
