# Generated by Django 3.1.2 on 2020-10-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_earning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Earning',
            new_name='Earning_data',
        ),
    ]
