# Generated by Django 3.1.2 on 2020-10-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201030_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='postalcode',
            field=models.IntegerField(null=True),
        ),
    ]
