# Generated by Django 3.1.2 on 2020-10-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
