# Generated by Django 3.1.2 on 2020-10-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person_id',
        ),
    ]
